/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package start;

import java.awt.Graphics;

/**
 *
 * @author Daniel Latos
 */
public class Start extends javax.swing.JFrame {
    private boolean penStatus = false;
    private int x = 300, y = 300, location_x = 0, location_y = 0;
    private String direction = "NORTH";

     //To change body of generated methods, choose Tools | Templates.

    
    /**
     * Creates new form Start
     */
    public Start() {
        initComponents();
        super.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        quit_button = new javax.swing.JButton();
        clean_button = new javax.swing.JButton();
        forward_button = new javax.swing.JButton();
        right_button = new javax.swing.JButton();
        left_button = new javax.swing.JButton();
        penDown_button = new javax.swing.JButton();
        penUp_button = new javax.swing.JButton();
        penStatus_textField = new javax.swing.JTextField();
        angle_textField = new javax.swing.JTextField();
        location_textField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        quit_button.setText("quit");
        quit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quit_buttonActionPerformed(evt);
            }
        });

        clean_button.setText("clean");
        clean_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_buttonActionPerformed(evt);
            }
        });

        forward_button.setText("forward");
        forward_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forward_buttonActionPerformed(evt);
            }
        });

        right_button.setText("right");
        right_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_buttonActionPerformed(evt);
            }
        });

        left_button.setText("left");
        left_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_buttonActionPerformed(evt);
            }
        });

        penDown_button.setText("pen down");
        penDown_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penDown_buttonActionPerformed(evt);
            }
        });

        penUp_button.setText("pen up");
        penUp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penUp_buttonActionPerformed(evt);
            }
        });

        penStatus_textField.setEditable(false);
        penStatus_textField.setText("Pen: up");

        angle_textField.setEditable(false);
        angle_textField.setText("Angle: 0 ");

        location_textField.setEditable(false);
        location_textField.setText("X, Y: 0, 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(penDown_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(penUp_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(left_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(forward_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(right_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clean_button, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                            .addComponent(quit_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(penStatus_textField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(angle_textField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(location_textField, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(location_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(angle_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(penStatus_textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 434, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clean_button)
                    .addComponent(penUp_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quit_button)
                    .addComponent(right_button)
                    .addComponent(forward_button)
                    .addComponent(left_button)
                    .addComponent(penDown_button))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quit_buttonActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_quit_buttonActionPerformed

    private void penDown_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penDown_buttonActionPerformed
        penStatus = true; 
        penStatus_textField.setText("Pen: down"); // TODO add your handling code here:
    }//GEN-LAST:event_penDown_buttonActionPerformed

    private void penUp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penUp_buttonActionPerformed
        penStatus = false;
        penStatus_textField.setText("Pen: up");        // TODO add your handling code here:
    }//GEN-LAST:event_penUp_buttonActionPerformed

    private void forward_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forward_buttonActionPerformed
        Graphics g = jPanel1.getGraphics();
        
        if(penStatus == true)
        {
            switch(direction)
            {
                case "NORTH":
                    g.drawLine(x, y, x, y-25);
                    y -= 25;
                    location_y += 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "SOUTH":
                    g.drawLine(x, y, x, y+25);
                    y += 25;
                    location_y -= 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "WEST":
                    g.drawLine(x, y, x-25, y);
                    x -= 25;
                    location_x -= 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "EAST":
                    g.drawLine(x, y, x+25, y);
                    x += 25;
                    location_x += 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                default:
                    break;
                    
            }
            
        }
        else
        {
            switch(direction)
            {
                case "NORTH":
                    //g.drawLine(x, y, x, y-25);
                    y -= 25;
                    location_y += 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "SOUTH":
                    //g.drawLine(x, y, x, y+25);
                    y += 25;
                    location_y -= 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "WEST":
                    //g.drawLine(x, y, x-25, y);
                    x -= 25;
                    location_x -= 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                case "EAST":
                    //g.drawLine(x, y, x+25, y);
                    x += 25;
                    location_x += 25;
                    location_textField.setText("X, Y: "+ (location_x) +", "+ (location_y));
                    break;
                default:
                    break;
                    
            }
        }
    }//GEN-LAST:event_forward_buttonActionPerformed

    private void clean_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_buttonActionPerformed
        repaint();
        x = 300; y = 300;
        location_x = 0; location_y = 0;
        direction = "NORTH";
        angle_textField.setText("Angle: 0");
        location_textField.setText("X, Y: 0, 0");
    }//GEN-LAST:event_clean_buttonActionPerformed

    private void right_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_buttonActionPerformed
        switch(direction)
        {
            case "NORTH":
                direction = "EAST";
                angle_textField.setText("Angle: 90");
                break;
            case "SOUTH":
                direction = "WEST";
                angle_textField.setText("Angle: 270");
                break;
            case "WEST":
                direction = "NORTH";
                angle_textField.setText("Angle: 0");
                break;
            case "EAST":
                direction = "SOUTH";
                angle_textField.setText("Angle: 180");
                break;
            default:
                break;
        }// TODO add your handling code here:
    }//GEN-LAST:event_right_buttonActionPerformed

    private void left_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_buttonActionPerformed
        switch(direction)
        {
            case "NORTH":
                direction = "WEST";
                angle_textField.setText("Angle: 270");
                break;
            case "SOUTH":
                direction = "EAST";
                angle_textField.setText("Angle: 90");
                break;
            case "WEST":
                direction = "SOUTH";
                angle_textField.setText("Angle: 180");
                break;
            case "EAST":
                direction = "NORTH";
                angle_textField.setText("Angle: 0");
                break;
            default:
                break;
        }// TODO add your handling code here
    }//GEN-LAST:event_left_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Start().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField angle_textField;
    private javax.swing.JButton clean_button;
    private javax.swing.JButton forward_button;
    javax.swing.JPanel jPanel1;
    private javax.swing.JButton left_button;
    private javax.swing.JTextField location_textField;
    private javax.swing.JButton penDown_button;
    private javax.swing.JTextField penStatus_textField;
    private javax.swing.JButton penUp_button;
    private javax.swing.JButton quit_button;
    private javax.swing.JButton right_button;
    // End of variables declaration//GEN-END:variables
}
